Models/AlertBike.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BikeWatcher.Models
{
    public class AlertBike
    {
        public int ID { get; set; }
        public int numberBike { get; set; }
        public string message { get; set; }

    }
}

Models/BikeStation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BikeWatcher.Models
{
    public class BikeStation
    {
        public BikeStation()
        {

        }

        public BikeStation(BikeStationBdx bikeStationBdx)
        {
            this.gid = bikeStationBdx.id.ToString();
            this.lat = bikeStationBdx.latitude;
            this.lng = bikeStationBdx.longitude;
            this.address = "Aucune adresse de disponible";
            this.name = bikeStationBdx.name;
            this.available_bikes = bikeStationBdx.bike_count.ToString();
            this.bike_stands = bikeStationBdx.slot_count.ToString();

            if (bikeStationBdx.is_online)
            {
                this.status = "OPEN";
            }
            else
            {
                this.status = "CLOSE";

            }


        }

        public string number { get; set; }
        public string pole { get; set; }
        public string available_bikes { get; set; }
        public string code_insee { get; set; }
        public string lng { get; set; }
        public string availability { get; set; }
        public string availabilitycode { get; set; }
        public string etat { get; set; }
        public string startdate { get; set; }
        public string langue { get; set; }
        public string bike_stands { get; set; }
        public string last_update { get; set; }
        public string available_bike_stands { get; set; }
        public string gid { get; set; }
        public string titre { get; set; }
        public string status { get; set; }
        public string commune { get; set; }
        public string description { get; set; }
        public string nature { get; set; }
        public string bonus { get; set; }
        public string address2 { get; set; }
        public string address { get; set; }
        public string lat { get; set; }
        public string last_update_fme { get; set; }
        public string enddate { get; set; }
        public string name { get; set; }
        public string banking { get; set; }
        public string nmarrond { get; set; }
    }
}

Models/BikeStationBdx.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BikeWatcher.Models
{
    public class BikeStationBdx
    {
        public int id { get; set; }
        public string name { get; set; }
        public int bike_count { get; set; }
        public int electric_bike_count { get; set; }
        public int bike_count_total { get; set; }
        public int slot_count { get; set; }
        public bool is_online { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
    }
}

Models/BikeStationJson.cs
using System.Collections.Generic;

namespace BikeWatcher.Models
{
    public class BikeStationJson
    {
        public List<string> fields { get; set; }
        public List<BikeStation> values { get; set; }
        public int nb_results { get; set; }
        public string table_href { get; set; }
        public string layer_name { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace BikeWatcher.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/FavBikeStations.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BikeWatcher.Models
{
    public class FavBikeStations
    {
        public int ID { get; set; }
        public int idFav { get; set; }
    }
}

Controllers/BikeStationController.cs
using Microsoft.AspNetCore.Mvc;
using System.Net.Http;
using System.Threading.Tasks;
using System.Data;
using System.Linq;
using System.Diagnostics;
using System.Text.Json;
using BikeWatcher.Models;
using System.Collections.Generic;
using BikeWatcher.Data;
using Microsoft.EntityFrameworkCore;

namespace BikeWatcher.Controllers
{
    public class BikeStationController : Controller
    {
        private static readonly HttpClient client = new HttpClient();

        private readonly BikeWatcherContext _context;

        public BikeStationController(BikeWatcherContext context)
        {
            _context = context;
        }

        static async Task<List<BikeStation>> GetBikeStationsAsync(string city)
        {
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Add("User-Agent", ".NET Foundation Repository Reporter");

            if (city.ToLower() == "bordeaux")
            {
                var streamTaskBdx = client.GetStreamAsync("https://api.alexandredubois.com/vcub-backend/vcub.php");
                var bikeStationsBdx = await JsonSerializer.DeserializeAsync<List<BikeStationBdx>>(await streamTaskBdx);
                var bikeStations = new List<BikeStation>();
                foreach (var bikeStationBdx in bikeStationsBdx)
                {
                    var bikeStation = new BikeStation(bikeStationBdx);
                    bikeStations.Add(bikeStation);
                }
                return bikeStations;
            }

            var streamTask = client.GetStreamAsync("https://download.data.grandlyon.com/ws/rdata/jcd_jcdecaux.jcdvelov/all.json");
            var bikeStationJson = await JsonSerializer.DeserializeAsync<BikeStationJson>(await streamTask);
            return bikeStationJson.values;

        }

        public async Task<IActionResult> Index(string city = "lyon")
        {
            var bikeStations = await GetBikeStationsAsync(city);
            ViewBag.bikeStations = bikeStations.OrderBy(x => x.name);
            return View();
        }

        public async Task<IActionResult> MapAsync(string city = "lyon")
        {
            var bikeStations = await GetBikeStationsAsync(city);
            ViewBag.bikeStations = bikeStations;
            return View();
        }

        public async Task<IActionResult> AddToFav(int id)
        {
            var favBikeStation = new FavBikeStations();
            favBikeStation.idFav = id;
            _context.FavBikeStations.Add(favBikeStation);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
            
        }

        public IActionResult AlertBike()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AlertBike([Bind("numberBike, message")] AlertBike alertBike)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(alertBike);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (DbUpdateException /* ex */)
            {
                //Log the error (uncomment ex variable name and write a log.
                ModelState.AddModelError("", "Unable to save changes. " +
                    "Try again, and if the problem persists " +
                    "see your system administrator.");
            }
            return View(alertBike);
        }

        public async Task<IActionResult> FavoriteAsync()
        {
            return View(await _context.FavBikeStations.ToListAsync());
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using BikeWatcher.Models;

namespace BikeWatcher.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/BikeStation/AlertBike.cshtml
@model BikeWatcher.Models.AlertBike
@{
    ViewData["Title"] = "Alert a Bike";
}

<h1>Signaler un vélo défectueux</h1>

<form asp-action="AlertBike">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="numberBike" class="control-label"></label>
        <input asp-for="numberBike" class="form-control" />
        <span asp-validation-for="numberBike" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="message" class="control-label"></label>
        <input asp-for="message" class="form-control" />
        <span asp-validation-for="message" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Envoyer" class="btn btn-primary" />
    </div>
</form>

Views/BikeStation/Favorite.cshtml
@model IEnumerable<BikeWatcher.Models.FavBikeStations>

@{
    ViewData["Title"] = "Favorites";
}

<div class="container">
    <div class="text-center">
        <h1 class="display-4">Mes Favoris</h1>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">IDFAV</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var favori in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => favori.ID)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => favori.idFav)
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>

Views/BikeStation/Index.cshtml
@{
    ViewData["Title"] = "Listes des stations";
    var bikeStations = ViewBag.bikeStations;
}

<div class="container">
    <div class="text-center">
        <h1 class="display-4">Bike Stations</h1>


        <p>@Html.ActionLink("Lyon", "Index", new { city = "lyon" }) / @Html.ActionLink("Bordeaux", "Index", new { city = "Bordeaux" })</p>


        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Nom</th>
                    <th scope="col">Vélos disponibles</th>
                    <th scope="col">Adresse</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var bikeStation in bikeStations)
                {
                    <tr>
                        <th scope="row">@bikeStation.name</th>
                        <td>@bikeStation.available_bikes</td>
                        <td>@bikeStation.address</td>
                        <td>
                            <a asp-action="AddToFav" asp-route-id="@bikeStation.gid">Ajouter aux favoris</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>

Views/BikeStation/Map.cshtml
@{
    ViewData["Title"] = "Map";
    var bikeStations = ViewBag.bikeStations;
}
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css" integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ==" crossorigin="" />
<style type="text/css">
    #map { /* la carte DOIT avoir une hauteur sinon elle n'apparaît pas */
        height: 400px;
    }
</style>


<p>@Html.ActionLink("Lyon", "Map", new { city = "lyon" }) / @Html.ActionLink("Bordeaux", "Map", new { city = "Bordeaux" })</p>


<div id="map">
    <!-- Ici s'affichera la carte -->
</div>

<!-- Fichiers Javascript -->
<script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js" integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw==" crossorigin=""></script>
<script type="text/javascript">

    // Fonction d'initialisation de la carte
    function initMap() {
        // Créer l'objet "macarte" et l'insèrer dans l'élément HTML qui a l'ID "map"
        macarte = L.map('map').setView([lat, lon], 11);
        // Leaflet ne récupère pas les cartes (tiles) sur un serveur par défaut. Nous devons lui préciser où nous souhaitons les récupérer. Ici, openstreetmap.fr
        L.tileLayer('https://{s}.tile.openstreetmap.fr/osmfr/{z}/{x}/{y}.png', {
            // Il est toujours bien de laisser le lien vers la source des données
            attribution: 'données © <a href="//osm.org/copyright">OpenStreetMap</a>/ODbL - rendu <a href="//openstreetmap.fr">OSM France</a>',
            minZoom: 1,
            maxZoom: 20
        }).addTo(macarte);
        for (bikeStation in bikeStations) {
                var marker = L.marker([bikeStations[bikeStation].lat, bikeStations[bikeStation].lon]).addTo(macarte);
                marker.bindPopup("<p> Nombre de vélos : "+ bikeStations[bikeStation].available_bikes + "</p> <p> Adresses : " + bikeStations[bikeStation].address + "</p>");
        }
    }
    // On initialise la latitude et la longitude de Paris (centre de la carte)
    var lat = 45.75;
    var lon = 4.85;

    var options = {
      enableHighAccuracy: true,
      timeout: 5000,
      maximumAge: 0
    };

    function success(pos) {
      var crd = pos.coords;
        lat = crd.latitude
        lon = crd.longitude
        var macarte = null;
        initMap()
    }

    function error(err) {
        initMap()
    }
         var bikeStations = [

            @foreach (var bikeStation in bikeStations)
            {
                <text>
                    {
                        "address": "@bikeStation.address",
                        "lat": "@bikeStation.lat",
                        "lon": "@bikeStation.lng",
                        "available_bikes": "@bikeStation.available_bikes"
                    },

                </text>


        }];

    window.onload = function () {
        // Fonction d'initialisation qui s'exécute lorsque le DOM est chargé
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(success, error, options)
            Location.reload()
        }


    };
</script>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="container">
    <div class="text-center">
        <h1 class="display-4">Kévin Monnot Etudiant en Informatique</h1>
        <p>Voir mon <a href="https://github.com/Riukotashi/BikeWatcher">projet Github</a></p>
    </div>
    <ul class="list-group">
        <li ul class="list-group-item" style="text-decoration: line-through;">
            Avoir une application ASP.Net Core de base nommée "BikeWatcher" qui tourne sur sa machine
        </li>
        <li ul class="list-group-item" style="text-decoration: line-through;">
            Créer un repository public sur github, bitbucket ou gitlab pour héberger votre code.
        </li>
        <li ul class="list-group-item" style="text-decoration: line-through;">
            Publier votre code sur le repository à chaque avancée
        </li>
        <li ul class="list-group-item" style="text-decoration: line-through;">
            Supprimer du menu les pages de bases pour 2 liens de menu fonctionnels vers les pages vides suivantes : "Accueil", "Liste des stations", "Carte", "Mes favoris"
        </li>
        <li ul class="list-group-item" style="text-decoration: line-through;">
            Compléter la pages "Accueil" pour présenter votre travail, votre nom/prenom, cette liste d'objectifs (que vous rayerez au fur et à mesure) et l'URL où votre code source est visible
        </li>
        <li ul class="list-group-item" style="text-decoration: line-through;">
            Se brancher sur l'API VeloV du grand Lyon pour récupérer les données en temps réel
        </li>
        <li ul class="list-group-item" style="text-decoration: line-through;">
            Afficher les données de l'API sous forme de tableau sur la page "Liste des stations" (les stations sont triées par ordre alphabétique)
        </li>
        <li ul class="list-group-item" style="text-decoration: line-through;">
            Afficher les données de l'API sous forme de carte sur la page "Carte" (chaque station sera représentée par une épingle à son emplacement)
        </li>
        <li ul class="list-group-item" style="text-decoration: line-through;">
            Ajouter sur caque épingle de la carte la possibilité de cliquer pour afficher une infobulle qui indiquera le nombre de vélos et de places à la station en question
        </li>
        <li ul class="list-group-item">
            Ajouter la possibilité de créer un compte utilisateur sur votre application
        </li>
        <li ul class="list-group-item" style="text-decoration: line-through;">
            Ajouter sur la page "Liste des stations" et/ou "Carte" la possibilité de rajouter des stations en favoris
        </li>
        <li ul class="list-group-item" style="text-decoration: line-through;">
            Compléter la page "Mes favoris" pour n'afficher sous forme de tableau que les stations marquées en favoris
        </li>
        <li ul class="list-group-item" style="text-decoration: line-through;">
            Stocker les stations favorites dans une base SQL
        </li>
        <li ul class="list-group-item" style="text-decoration: line-through;">
            Centrer automatiquement la carte par rapport à la position de l'utilisateur
        </li>
        <li ul class="list-group-item">
            Trier automatiquement la liste des stations par rapport à la position de l'utilisateur
        </li>
        <li ul class="list-group-item">
            Rendre votre application bilingue Français / Anglais
        </li>
        <li ul class="list-group-item" style="text-decoration: line-through;">
            Rendre votre application utilisable à la fois pour la ville de Lyon et la ville de Bordeaux (par exemple un bouton permettra de passer de l'un à l'autre dans le menu)
        </li>
        <li ul class="list-group-item">
            Déployer votre code sur un serveur accessible publiquement en consultation
        </li>
        <li ul class="list-group-item" style="text-decoration: line-through;">
            Permettre aux utilisateurs de signaler un vélo en panne
        </li>
        <li ul class="list-group-item" style="text-decoration: line-through;">
            Faire en sorte que votre site soit agréable à utiliser sur mobile (il ne doit pas comporter ascenseur horizontal)
        </li>
        <li ul class="list-group-item">
            BONUS : toute fonctionnalité supplémentaire sera valorisée, pensez-juste à l'indiquer sur votre page d'accueil que je puisse la comptabiliser
        </li>


    </ul>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BikeWatcher</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BikeWatcher</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Accueil</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BikeStation" asp-action="Index">Liste des stations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BikeStation" asp-action="Map">Carte</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BikeStation" asp-action="Favorite">Mes favoris</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - BikeWatcher - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>